CREATE TABLE PHONGTRO (
    MAPT CHAR(5) PRIMARY KEY,
    TENPT NVARCHAR(50),
    DIENTICH FLOAT,
    GIAPT MONEY,
    TINHTRANGPT NVARCHAR(20)
);

CREATE TABLE CUDAN (
    MACD CHAR(5) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    CCCD NVARCHAR(12),
    DIACHI NVARCHAR(100),
    SODT VARCHAR(15),
    NGAYTHUE SMALLDATETIME,
    TRANGTHAICD NVARCHAR(15)
);

CREATE TABLE HOPDONG (
    MAHD CHAR(5) PRIMARY KEY,
    MACD CHAR(5),
    MAPT CHAR(5),
    NGAYKY SMALLDATETIME,
    NGAYHETHAN SMALLDATETIME,
    TRANGTHAIHD NVARCHAR(20),
    FOREIGN KEY (MACD) REFERENCES CUDAN(MACD),
    FOREIGN KEY (MAPT) REFERENCES PHONGTRO(MAPT)
);

CREATE TABLE DICHVU (
    MADV CHAR(5) PRIMARY KEY,
    TENDV NVARCHAR(50),
    DONGIA MONEY
);

CREATE TABLE PHIEUTINHTIEN (
    MAPTT CHAR(5) PRIMARY KEY,
    MAHD CHAR(5),
    SOTIENDICHVU MONEY,
    SOTIENTHUEPT MONEY,
    TONGTIENTT MONEY,
    NGAYTINHTIEN SMALLDATETIME,
    TINHTRANGTT NVARCHAR(20),
    PHUONGTHUCTT NVARCHAR(20),
    FOREIGN KEY (MAHD) REFERENCES HOPDONG(MAHD)
);

CREATE TABLE CHITIETTTDV (
    MAPTT CHAR(5) ,
    MADV CHAR(5),
    CHISODV FLOAT,
    THANHTIEN MONEY,
    PRIMARY KEY ( MAPTT,MADV),
    FOREIGN KEY (MADV) REFERENCES DICHVU(MADV),
    FOREIGN KEY (MAPTT) REFERENCES PHIEUTINHTIEN(MAPTT)
);


ALTER TABLE PHONGTRO ADD CHECK ( DIENTICH BETWEEN 10 AND 50 );

ALTER TABLE PHIEUTINHTIEN ADD CHECK ( TINHTRANGTT IN ( 'Chua thanh toan','Da thanh toan'));
SELECT PT.MAPT,PT.TENPT,CD.MACD,HOTEN
FROM PHONGTRO PT
JOIN HOPDONG HD
ON PT.MAPT=HD.MAPT
JOIN CUDAN CD
ON HD.MACD=CD.MACD
WHERE GIAPT>5000000 AND YEAR(NGAYKY)=2024;

(SELECT DV.MADV,TENDV
FROM DICHVU DV
JOIN CHITIETTTDV CT
ON DV.MADV=CT.MADV
JOIN PHIEUTINHTIEN PTT
ON PTT.MAPTT=CT.MAPTT
WHERE MONTH(NGAYTINHTIEN)=11 AND YEAR(NGAYTINHTIEN)=2024 AND MAHD='HD002' AND TINHTRANGTT='Da thanh toan')
INTERSECT
(SELECT DV.MADV,TENDV
FROM DICHVU DV
JOIN CHITIETTTDV CT
ON DV.MADV=CT.MADV
JOIN PHIEUTINHTIEN PTT
ON PTT.MAPTT=CT.MAPTT
WHERE MONTH(NGAYTINHTIEN)=12 AND YEAR(NGAYTINHTIEN)=2024 AND MAHD='HD002' AND TINHTRANGTT='Da thanh toan')

SELECT PTT.MAPTT,PTT.MAHD
FROM PHIEUTINHTIEN PTT
WHERE YEAR(NGAYTINHTIEN) =2024 AND NOT EXISTS ( SELECT 1 FROM DICHVU DV
                                                  WHERE DV.DONGIA<=150000 AND NOT EXISTS ( SELECT 1 FROM CHITIETTTDV CT
                                                  WHERE CT.MADV=DV.MADV AND CT.MAPTT=PTT.MAPTT));
SELECT HD.MAHD,HD.MACD,COUNT(PTT.MAPTT) AS SLPTT
FROM HOPDONG HD
JOIN PHIEUTINHTIEN PTT
ON HD.MAHD=PTT.MAHD
WHERE YEAR(NGAYTINHTIEN)=2024 AND PHUONGTHUCTT='Chuyen khoan'
GROUP BY HD.MAHD,HD.MACD;

SELECT CD.MACD,HOTEN
FROM CUDAN CD
JOIN HOPDONG HD
ON CD.MACD=HD.MACD
JOIN PHIEUTINHTIEN PTT
ON HD.MAHD=PTT.MAHD
WHERE CD.MACD IN ( SELECT TOP 1 WITH TIES HD1.MACD FROM HOPDONG HD1
                    GROUP BY HD1.MACD
                    ORDER BY COUNT(*) DESC)
AND YEAR(PTT.NGAYTINHTIEN)=2024
GROUP BY CD.MACD,HOTEN
HAVING SUM(PTT.TONGTIENTT) >=15000000;





